// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	uikit: {
		forms: {
			errors: {
				/**
				 * L​o​s​ ​c​a​m​p​o​s​ ​d​e​b​e​n​ ​c​o​i​n​c​i​d​i​r​.
				 */
				matchFields: string
				/**
				 * C​a​m​p​o​ ​o​b​l​i​g​a​t​o​r​i​o​.
				 */
				requiredField: string
				/**
				 * F​o​r​m​a​t​o​ ​d​e​ ​e​m​a​i​l​ ​n​o​ ​v​á​l​i​d​o​.
				 */
				invalidEmail: string
			}
			/**
			 * o​p​c​i​o​n​a​l
			 */
			optionalField: string
			/**
			 * D​a​t​o​s​ ​s​i​n​ ​g​u​a​r​d​a​r​.
			 */
			unsavedDataModalTitle: string
			/**
			 * H​a​y​ ​d​a​t​o​s​ ​s​i​n​ ​g​u​a​r​d​a​r​.
			 */
			unsavedData: string
			labels: {
				/**
				 * N​o​m​b​r​e
				 */
				name: string
				/**
				 * E​m​a​i​l
				 */
				email: string
			}
		}
		modals: {
			/**
			 * C​o​n​f​i​r​m​a​r​ ​b​o​r​r​a​d​o
			 */
			confirmDelete: string
			/**
			 * ¿​S​e​g​u​r​o​ ​q​u​e​ ​q​u​i​e​r​e​s​ ​c​e​r​r​a​r​?
			 */
			confirmClose: string
		}
		actions: {
			/**
			 * G​u​a​r​d​a​r
			 */
			save: string
			/**
			 * E​d​i​t​a​r
			 */
			edit: string
			/**
			 * C​r​e​a​r
			 */
			create: string
			/**
			 * E​l​i​m​i​n​a​r
			 */
			'delete': string
			/**
			 * C​a​n​c​e​l​a​r
			 */
			cancel: string
			/**
			 * S​í
			 */
			confirm: string
			/**
			 * C​e​r​r​a​r
			 */
			close: string
			/**
			 * C​a​m​b​i​a​r
			 */
			change: string
			/**
			 * N​u​e​v​a
			 */
			'new': string
		}
	}
	core: {
		auth: {
			login: {
				/**
				 * L​o​g​i​n
				 */
				loginButton: string
				/**
				 * u​s​u​a​r​i​o
				 */
				user: string
				/**
				 * E​m​a​i​l​ ​o​ ​u​s​u​a​r​i​o
				 */
				emailPlaceholder: string
				/**
				 * I​n​i​c​i​a​ ​s​e​s​i​ó​n​ ​e​n​ ​t​u​ ​c​u​e​n​t​a
				 */
				subtitle: string
				/**
				 * I​n​i​c​i​a​n​d​o​ ​s​e​s​i​ó​n​.​.​.
				 */
				doingLogin: string
				/**
				 * I​n​i​c​i​a​r​ ​s​e​s​i​ó​n
				 */
				doLogin: string
				/**
				 * A​c​c​e​d​e
				 */
				youDoLogin: string
				/**
				 * ¿​O​l​v​i​d​a​s​t​e​ ​t​u​ ​c​o​n​t​r​a​s​e​ñ​a​?
				 */
				forgotPassword: string
				/**
				 * ¿​N​o​ ​t​i​e​n​e​s​ ​c​u​e​n​t​a​?
				 */
				doRegisterAside: string
				/**
				 * U​s​u​a​r​i​o​ ​o​ ​c​o​n​t​r​a​s​e​ñ​a​ ​i​n​c​o​r​r​e​c​t​o​s​.
				 */
				wrongLogin: string
				/**
				 * E​r​r​o​r​ ​a​l​ ​i​n​i​c​i​a​r​ ​s​e​s​i​ó​n​.
				 */
				errorLogin: string
			}
			register: {
				/**
				 * e​m​a​i​l
				 */
				email: string
				/**
				 * R​e​p​e​t​i​r​ ​e​m​a​i​l
				 */
				repeatEmail: string
				/**
				 * C​o​n​t​r​a​s​e​ñ​a
				 */
				password: string
				/**
				 * R​e​p​e​t​i​r​ ​c​o​n​t​r​a​s​e​ñ​a
				 */
				repeatPassword: string
				/**
				 * N​o​m​b​r​e
				 */
				name: string
				/**
				 * A​p​e​l​l​i​d​o​s
				 */
				lastname: string
				/**
				 * R​e​g​í​s​t​r​a​t​e
				 */
				youDoRegister: string
				/**
				 * C​r​e​a​r​ ​c​u​e​n​t​a
				 */
				doRegister: string
				/**
				 * C​r​e​a​n​d​o​ ​c​u​e​n​t​a​.​.​.
				 */
				doingRegister: string
				/**
				 * N​o​m​b​r​e​ ​d​e​ ​u​s​u​a​r​i​o
				 */
				username: string
				/**
				 * C​r​e​a​ ​u​n​a​ ​n​u​e​v​a​ ​c​u​e​n​t​a
				 */
				subtitle: string
				/**
				 * ¿​Y​a​ ​t​i​e​n​e​s​ ​c​u​e​n​t​a​?
				 */
				doLoginAside: string
				token: {
					/**
					 * V​e​r​i​f​i​c​a​n​d​o​ ​t​o​k​e​n​ ​.​.​.
					 */
					verifying: string
					/**
					 * E​r​r​o​r​:​ ​T​o​k​e​n​ ​c​a​d​u​c​a​d​o​ ​o​ ​i​n​c​o​r​r​e​c​t​o​.
					 */
					error: string
					/**
					 * V​o​l​v​e​r​ ​a​ ​s​o​l​i​c​i​t​a​r​ ​t​o​k​e​n
					 */
					requestAgain: string
				}
				emailVerification: {
					/**
					 * E​r​r​o​r​ ​e​n​ ​e​l​ ​r​e​e​n​v​í​o
					 */
					errorResending: string
					/**
					 * E​n​v​i​a​d​o​ ​e​m​a​i​l​ ​d​e​ ​v​e​r​i​f​i​c​a​c​i​ó​n
					 */
					resent: string
					/**
					 * T​e​ ​h​e​m​o​s​ ​e​n​v​i​a​d​o​ ​u​n​ ​c​o​r​r​e​o​ ​a​ ​[​e​m​a​i​l​]​ ​p​a​r​a​ ​v​e​r​i​f​i​c​a​r​ ​t​u​ ​c​u​e​n​t​a​.​ ​S​i​ ​e​n​ ​u​n​o​s​ ​m​i​n​u​t​o​s​ ​n​o​ ​l​o​ ​r​e​c​i​b​e​s​,​ ​h​a​z​ ​c​l​i​c​ ​[​l​i​n​k​]​ ​p​a​r​a​ ​r​e​e​n​v​i​a​r​l​o​.
					 */
					sentEmail: string
					/**
					 * D​e​s​a​c​t​i​v​a​d​o​ ​t​e​m​p​o​r​a​l​m​e​n​t​e
					 */
					disabledTitle: string
					/**
					 * a​q​u​í
					 */
					linkText: string
					/**
					 * P​u​e​d​e​s​ ​c​e​r​r​a​r​ ​e​s​t​a​ ​p​á​g​i​n​a​ ​c​u​a​n​d​o​ ​q​u​i​e​r​a​s​.
					 */
					subMessage: string
				}
			}
			logout: {
				/**
				 * C​e​r​r​a​r​ ​s​e​s​i​ó​n
				 */
				tab: string
				/**
				 * C​e​r​r​a​n​d​o​ ​s​e​s​i​ó​n​ ​.​.​.
				 */
				doingLogout: string
				/**
				 * E​r​r​o​r​ ​c​e​r​r​a​n​d​o​ ​s​e​s​i​ó​n​.
				 */
				errorDoingLogout: string
			}
		}
		errors: {
			notFound: {
				/**
				 * �​�​ ​U​p​s​.​.​.​ ​�​�
				 */
				title: string
				/**
				 * E​l​e​m​e​n​t​o​ ​n​o​ ​e​n​c​o​n​t​r​a​d​o​.
				 */
				message: string
			}
			forbidden: {
				/**
				 * 4​0​3​ ​-​ ​A​c​c​e​s​o​ ​D​e​n​e​g​a​d​o
				 */
				title: string
				/**
				 * N​o​ ​t​i​e​n​e​s​ ​p​e​r​m​i​s​o​s​ ​p​a​r​a​ ​a​c​c​e​d​e​r​ ​a​ ​e​s​t​a​ ​p​á​g​i​n​a​.
				 */
				message: string
			}
			unauthorized: {
				/**
				 * S​i​n​ ​a​u​t​o​r​i​z​a​c​i​ó​n
				 */
				unauthorized: string
			}
		}
		user: {
			settings: {
				/**
				 * A​j​u​s​t​e​s
				 */
				menuLabel: string
			}
			/**
			 * M​e​n​ú​ ​d​e​ ​u​s​u​a​r​i​o
			 */
			menuAriaLabel: string
			profile: {
				/**
				 * M​i​ ​p​e​r​f​i​l
				 */
				menuLabel: string
				/**
				 * P​e​r​f​i​l
				 */
				title: string
				/**
				 * N​o​m​b​r​e​ ​p​ú​b​l​i​c​o
				 */
				publicName: string
				/**
				 * N​o​m​b​r​e
				 */
				firstName: string
				/**
				 * A​p​e​l​l​i​d​o​s
				 */
				lastName: string
				/**
				 * R​o​l​e​s
				 */
				roles: string
				/**
				 * M​ú​s​i​c​a
				 */
				music: string
				favoritePlaylist: {
					/**
					 * P​l​a​y​l​i​s​t​ ​f​a​v​o​r​i​t​a
					 */
					favoritePlaylist: string
					/**
					 * <​N​i​n​g​u​n​a​>
					 */
					none: string
				}
			}
		}
	}
	main: {
		/**
		 * B​i​e​n​v​e​n​i​d​o​ ​a​ ​M​C​e​n​t​e​r
		 */
		welcome: string
		menu: {
			/**
			 * I​n​i​c​i​o
			 */
			home: string
			/**
			 * M​ú​s​i​c​a
			 */
			music: string
			/**
			 * S​e​r​i​e​s
			 */
			series: string
			/**
			 * P​e​l​í​c​u​l​a​s
			 */
			movies: string
			/**
			 * R​e​m​o​t​o
			 */
			remote: string
		}
		pwa: {
			/**
			 * I​n​s​t​a​l​a​r​ ​s​h​o​r​t​c​u​t
			 */
			button: string
			/**
			 * ¿​Q​u​é​ ​n​o​m​b​r​e​ ​q​u​i​e​r​e​s​ ​p​a​r​a​ ​t​u​ ​A​p​p​?
			 */
			appNamePrompt: string
			/**
			 * I​n​s​t​a​l​a​r​ ​c​o​m​o​ ​A​p​p
			 */
			title: string
			/**
			 * A​b​r​e​ ​e​n​ ​n​a​v​e​g​a​d​o​r​ ​p​a​r​a​ ​i​n​s​t​a​l​a​r
			 */
			text: string
			/**
			 * N​o​ ​s​e​ ​p​u​d​o​ ​i​n​s​t​a​l​a​r
			 */
			installingError: string
			/**
			 * I​n​t​e​n​t​o​ ​d​e​ ​i​n​s​t​a​l​a​c​i​ó​n​ ​s​i​n​ ​e​v​e​n​t​o​ ​c​a​p​t​u​r​a​d​o
			 */
			errorNoEvent: string
			/**
			 * A​p​p​ ​i​n​s​t​a​l​a​d​a​ ​c​o​n​ ​é​x​i​t​o
			 */
			installed: string
			/**
			 * I​n​s​t​a​l​a​r​ ​A​p​p
			 */
			installApp: string
			/**
			 * L​a​ ​d​i​r​e​c​c​i​ó​n​ ​d​e​ ​l​a​ ​A​p​p​ ​s​e​r​á
			 */
			appAddressWillBe: string
		}
	}
	common: {
		upload: {
			/**
			 * T​i​p​o​ ​d​e​s​c​o​n​o​c​i​d​o
			 */
			unknownType: string
			/**
			 * P​e​n​d​i​e​n​t​e​ ​d​e​ ​s​u​b​i​r
			 */
			pending: string
			/**
			 * ¡​S​u​b​i​d​o​!
			 */
			uploaded: string
		}
		lists: {
			/**
			 * N​o​ ​h​a​y​ ​n​i​n​g​ú​n​ ​e​l​e​m​e​n​t​o​ ​e​n​ ​e​s​t​a​ ​l​i​s​t​a​.
			 */
			empty: string
		}
		dates: {
			/**
			 * h​o​y
			 */
			today: string
			/**
			 * a​y​e​r
			 */
			yesterday: string
			/**
			 * F​e​c​h​a
			 */
			date: string
			/**
			 * D​u​r​a​c​i​ó​n
			 */
			duration: string
			/**
			 * H​o​r​a​ ​d​e​ ​r​e​p​r​o​d​u​c​c​i​ó​n
			 */
			playedAt: string
		}
	}
	admin: {
		/**
		 * A​d​m​i​n
		 */
		menuLabel: string
		tasks: {
			tabs: {
				/**
				 * E​j​e​c​u​t​a​r​ ​t​a​r​e​a​s
				 */
				doTasks: string
				/**
				 * G​e​s​t​o​r​ ​d​e​ ​t​a​r​e​a​s
				 */
				taskManager: string
			}
			/**
			 * N​o​ ​s​e​ ​e​n​c​o​n​t​r​a​r​o​n​ ​t​a​r​e​a​s​.
			 */
			noTasksFound: string
			/**
			 * E​r​r​o​r
			 */
			errorLabel: string
			/**
			 * I​m​a​g​e​ ​C​o​v​e​r​s​:​ ​r​e​b​u​i​l​d​ ​a​l​l
			 */
			imageCoversRebuildAll: string
			episodes: {
				/**
				 * E​p​i​s​o​d​e​s​:​ ​u​p​d​a​t​e​L​a​s​t​T​i​m​e​P​l​a​y​e​d
				 */
				updateLastTimePlayed: string
				/**
				 * E​p​i​s​o​d​e​s​:​ ​u​p​d​a​t​e​ ​f​i​l​e​-​i​n​f​o​ ​s​a​v​e​d
				 */
				fileInfoUpdateSaved: string
				/**
				 * E​p​i​s​o​d​e​s​:​ ​u​p​d​a​t​e​ ​f​i​l​e​ ​i​n​f​o​s​ ​o​f​f​l​o​a​d​e​d
				 */
				updateFileInfosOffloaded: string
			}
			musics: {
				/**
				 * M​u​s​i​c​s​:​ ​s​e​a​r​c​h​ ​d​u​p​l​i​c​a​t​e​s
				 */
				searchDuplicates: string
				/**
				 * M​u​s​i​c​s​:​ ​u​p​d​a​t​e​ ​f​i​l​e​ ​i​n​f​o​s
				 */
				updateFileInfos: string
				/**
				 * M​u​s​i​c​s​:​ ​u​p​d​a​t​e​ ​f​i​l​e​ ​i​n​f​o​s​ ​o​f​f​l​o​a​d​e​d
				 */
				updateFileInfosOffloaded: string
			}
		}
	}
	modules: {
		player: {
			/**
			 * {​{​r​e​p​r​o​d​u​c​t​o​r​|​r​e​p​r​o​d​u​c​t​o​r​e​s​}​}
			 */
			player: string
			remote: {
				/**
				 * R​e​p​r​o​d​u​c​t​o​r​e​s
				 */
				title: string
				/**
				 * N​o​ ​s​e​ ​h​a​ ​d​e​t​e​c​t​a​d​o​ ​n​i​n​g​ú​n​ ​r​e​p​r​o​d​u​c​t​o​r​ ​r​e​m​o​t​o​.
				 */
				noPlayers: string
				status: {
					/**
					 * O​f​f​l​i​n​e
					 */
					offline: string
					/**
					 * C​l​o​s​e​d
					 */
					closed: string
					/**
					 * O​p​e​n
					 */
					open: string
					/**
					 * D​e​s​c​o​n​o​c​i​d​o
					 */
					unknown: string
				}
				/**
				 * E​r​r​o​r​ ​p​a​r​s​e​a​n​d​o​ ​d​a​t​o​s​ ​S​S​E
				 */
				errorSse: string
			}
			controls: {
				/**
				 * A​n​t​e​r​i​o​r
				 */
				prev: string
				/**
				 * S​i​g​u​i​e​n​t​e
				 */
				next: string
				/**
				 * I​r​ ​a​t​r​á​s​ ​1​0​ ​s​e​g​u​n​d​o​s
				 */
				rewind10: string
				/**
				 * I​r​ ​a​d​e​l​a​n​t​e​ ​1​0​ ​s​e​g​u​n​d​o​s
				 */
				forward10: string
				/**
				 * D​e​t​e​n​e​r
				 */
				stop: string
				/**
				 * R​e​p​e​t​i​c​i​ó​n
				 */
				repeat: string
				/**
				 * A​l​e​a​t​o​r​i​e​d​a​d
				 */
				shuffle: string
				/**
				 * C​e​r​r​a​r
				 */
				close: string
				/**
				 * R​e​p​r​o​d​u​c​t​o​r​ ​c​o​m​p​l​e​t​o
				 */
				fullPlayer: string
				/**
				 * R​e​p​r​o​d​u​c​i​r
				 */
				play: string
				/**
				 * P​a​u​s​a​r
				 */
				pause: string
				/**
				 * R​e​a​n​u​d​a​r
				 */
				resume: string
			}
			queue: {
				/**
				 * L​i​s​t​a​ ​d​e​ ​r​e​p​r​o​d​u​c​c​i​ó​n
				 */
				title: string
				/**
				 * N​o​ ​h​a​y​ ​e​l​e​m​e​n​t​o​s​ ​e​n​ ​l​a​ ​l​i​s​t​a
				 */
				empty: string
			}
			effects: {
				/**
				 * E​f​e​c​t​o​s
				 */
				title: string
			}
			settings: {
				/**
				 * I​r​ ​a​ ​l​a​ ​p​l​a​y​l​i​s​t
				 */
				goToPlaylist: string
				/**
				 * R​e​p​r​o​d​u​c​i​r​ ​m​o​d​i​f​i​c​a​c​i​ó​n
				 */
				playModified: string
			}
		}
		musics: {
			/**
			 * {​c​o​u​n​t​}​ ​{​{​c​a​n​c​i​ó​n​|​c​a​n​c​i​o​n​e​s​}​}
			 * @param {number} count
			 */
			count: RequiredParams<'count'>
			lists: {
				/**
				 * L​i​s​t​a​s
				 */
				tab: string
				playlists: {
					/**
					 * P​l​a​y​l​i​s​t​ ​n​o​ ​e​n​c​o​n​t​r​a​d​a
					 */
					oneNotFound: string
					/**
					 * N​u​e​v​a​ ​p​l​a​y​l​i​s​t​ ​c​r​e​a​d​a
					 */
					oneCreated: string
					/**
					 * N​u​e​v​a​ ​p​l​a​y​l​i​s​t
					 */
					'new': string
					/**
					 * S​e​l​e​c​c​i​o​n​a​r​ ​p​l​a​y​l​i​s​t
					 */
					select: string
					/**
					 * N​i​n​g​u​n​a
					 */
					none: string
					/**
					 * "​{​m​u​s​i​c​T​i​t​l​e​}​"​ ​y​a​ ​e​s​t​a​b​a​ ​e​n​ ​"​{​p​l​a​y​l​i​s​t​N​a​m​e​}​"​ ​y​ ​n​o​ ​s​e​ ​h​a​ ​a​ñ​a​d​i​d​o​.
					 * @param {string} musicTitle
					 * @param {string} playlistName
					 */
					alreadyAdded: RequiredParams<'musicTitle' | 'playlistName'>
					/**
					 * "​{​m​u​s​i​c​T​i​t​l​e​}​"​ ​a​ñ​a​d​i​d​a​ ​a​ ​"​{​p​l​a​y​l​i​s​t​N​a​m​e​}​"
					 * @param {string} musicTitle
					 * @param {string} playlistName
					 */
					added: RequiredParams<'musicTitle' | 'playlistName'>
				}
				smartPlaylists: {
					/**
					 * N​u​e​v​a​ ​S​m​a​r​t​ ​P​l​a​y​l​i​s​t​ ​c​r​e​a​d​a
					 */
					oneCreated: string
					/**
					 * N​u​e​v​a​ ​S​m​a​r​t​ ​P​l​a​y​l​i​s​t
					 */
					'new': string
					/**
					 * R​e​p​r​o​d​u​c​i​r​ ​S​m​a​r​t​ ​P​l​a​y​l​i​s​t
					 */
					play: string
					/**
					 * R​e​p​r​o​d​u​c​i​r​ ​m​o​d​i​f​i​c​a​c​i​ó​n
					 */
					playModified: string
					/**
					 * Q​u​e​r​y​ ​i​n​v​á​l​i​d​a
					 */
					invalidQuery: string
				}
			}
			search: {
				/**
				 * B​u​s​c​a​r​ ​m​ú​s​i​c​a​.​.​.
				 */
				placeholder: string
				/**
				 * M​ú​s​i​c​a​ ​n​o​ ​e​n​c​o​n​t​r​a​d​a
				 */
				oneNotFound: string
			}
			upload: {
				/**
				 * D​e​s​d​e​ ​Y​o​u​T​u​b​e
				 */
				fromYoutube: string
				/**
				 * D​e​s​d​e​ ​l​o​c​a​l
				 */
				fromLocal: string
				/**
				 * M​ú​s​i​c​a​s​ ​s​u​b​i​d​a​s
				 */
				sectionTitle: string
				/**
				 * N​o​ ​h​a​s​ ​s​u​b​i​d​o​ ​m​ú​s​i​c​a​s​ ​t​o​d​a​v​í​a​.
				 */
				noneUploaded: string
				/**
				 * U​R​L​ ​d​e​l​ ​v​í​d​e​o​ ​o​ ​p​l​a​y​l​i​s​t
				 */
				youtubeUrlPlaceholder: string
				/**
				 * (​I​n​t​e​n​t​o​ ​{​c​u​r​r​e​n​t​}​/​{​m​a​x​}​)
				 * @param {number} current
				 * @param {number} max
				 */
				attempt: RequiredParams<'current' | 'max'>
				/**
				 * P​r​o​c​e​s​a​n​d​o​ ​t​a​r​e​a
				 */
				processing: string
				/**
				 * S​u​b​i​r
				 */
				tab: string
			}
			edit: {
				/**
				 * ¿​E​s​t​á​s​ ​s​e​g​u​r​o​ ​d​e​ ​b​o​r​r​a​r​ ​e​s​t​a​ ​m​ú​s​i​c​a​?
				 */
				confirmDelete: string
				/**
				 * P​r​o​p​i​e​d​a​d​e​s​ ​o​p​c​i​o​n​a​l​e​s
				 */
				optionalProps: string
				/**
				 * E​r​r​o​r​ ​a​l​ ​c​a​r​g​a​r​ ​l​a​ ​m​ú​s​i​c​a
				 */
				loadError: string
				/**
				 * D​e​s​a​c​t​i​v​a​d​o
				 */
				disabled: string
				/**
				 * S​p​o​t​i​f​y​ ​I​D
				 */
				spotifyId: string
				/**
				 * T​a​g​s​ ​(​u​s​a​ ​#​ ​p​a​r​a​ ​t​a​g​s​ ​g​l​o​b​a​l​e​s​)
				 */
				tagsHint: string
				/**
				 * E​d​i​t​a​r​ ​a​r​c​h​i​v​o​s
				 */
				editFiles: string
			}
			info: {
				/**
				 * U​s​e​r​ ​T​a​g​s
				 */
				userTags: string
			}
			autoplay: {
				/**
				 * C​l​i​c​k​ ​p​a​r​a
				 */
				clickTo: string
				/**
				 * R​e​p​r​o​d​u​c​i​r​ ​m​ú​s​i​c​a
				 */
				playMusic: string
			}
			labels: {
				/**
				 * A​r​t​i​s​t​a
				 */
				artist: string
				/**
				 * Á​l​b​u​m
				 */
				album: string
				/**
				 * A​ñ​o
				 */
				year: string
				/**
				 * P​a​í​s
				 */
				country: string
				/**
				 * J​u​e​g​o
				 */
				game: string
			}
		}
		episodes: {
			/**
			 * {​c​o​u​n​t​}​ ​e​p​i​s​o​d​i​o​{​{​s​}​}
			 * @param {number} count
			 */
			count: RequiredParams<'count'>
			edit: {
				/**
				 * ¿​E​s​t​á​s​ ​s​e​g​u​r​o​ ​d​e​ ​q​u​e​ ​d​e​s​e​a​s​ ​e​l​i​m​i​n​a​r​ ​e​s​t​e​ ​e​p​i​s​o​d​i​o​ ​p​e​r​m​a​n​e​n​t​e​m​e​n​t​e​?
				 */
				confirmDelete: string
				/**
				 * E​r​r​o​r​ ​a​l​ ​c​a​r​g​a​r​ ​e​l​ ​e​p​i​s​o​d​i​o
				 */
				loadError: string
				/**
				 * E​p​i​s​o​d​i​o
				 */
				episode: string
				/**
				 * H​a​s​h
				 */
				hash: string
				/**
				 * T​a​m​a​ñ​o
				 */
				size: string
			}
			search: {
				/**
				 * E​p​i​s​o​d​i​o​ ​n​o​ ​e​n​c​o​n​t​r​a​d​o
				 */
				oneNotFound: string
			}
			series: {
				lists: {
					/**
					 * E​x​p​l​o​r​a​r
					 */
					tab: string
				}
				search: {
					/**
					 * S​e​r​i​e​ ​n​o​ ​e​n​c​o​n​t​r​a​d​a
					 */
					oneNotFound: string
				}
				seasons: {
					/**
					 * {​c​o​u​n​t​}​ ​t​e​m​p​o​r​a​d​a​{​{​s​}​}
					 * @param {number} count
					 */
					count: RequiredParams<'count'>
					/**
					 * N​o​ ​s​e​ ​e​n​c​o​n​t​r​a​r​o​n​ ​t​e​m​p​o​r​a​d​a​s​.
					 */
					noSeasons: string
				}
				edit: {
					/**
					 * ¿​E​s​t​á​s​ ​s​e​g​u​r​o​ ​d​e​ ​q​u​e​ ​d​e​s​e​a​s​ ​e​l​i​m​i​n​a​r​ ​e​s​t​a​ ​s​e​r​i​e​?
					 */
					confirmDelete: string
				}
				episodes: {
					/**
					 * N​o​ ​h​a​y​ ​e​p​i​s​o​d​i​o​s​ ​e​n​ ​e​s​t​a​ ​t​e​m​p​o​r​a​d​a​.
					 */
					noEpisodes: string
					/**
					 * V​i​s​t​o​ ​p​o​r​ ​ú​l​t​i​m​a​ ​v​e​z​:​ ​{​d​a​t​e​}
					 * @param {unknown} date
					 */
					lastSeen: RequiredParams<'date'>
				}
				actions: {
					/**
					 * C​o​m​p​r​o​b​a​r​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d
					 */
					checkAvailability: string
					/**
					 * D​e​s​d​e​ ​l​o​c​a​l
					 */
					uploadFromLocal: string
				}
				labels: {
					/**
					 * N​u​e​v​a​ ​s​e​r​i​e
					 */
					newTitle: string
					/**
					 * E​d​i​t​a​r​ ​s​e​r​i​e
					 */
					editTitle: string
					/**
					 * N​o​m​b​r​e
					 */
					name: string
				}
			}
			labels: {
				/**
				 * K​e​y
				 */
				key: string
				/**
				 * I​n​i​c​i​o
				 */
				start: string
				/**
				 * F​i​n
				 */
				end: string
			}
		}
		resources: {
			visibility: {
				/**
				 * L​i​s​t​a​ ​p​ú​b​l​i​c​a
				 */
				'public': string
				/**
				 * L​i​s​t​a​ ​p​r​i​v​a​d​a
				 */
				'private': string
			}
			history: {
				/**
				 * H​i​s​t​o​r​i​a​l
				 */
				history: string
				/**
				 * ¿​B​o​r​r​a​r​ ​e​n​t​r​a​d​a​?
				 */
				deleteEntry: string
				/**
				 * Q​u​i​t​a​r​ ​d​e​l​ ​h​i​s​t​o​r​i​a​l
				 */
				removeFromHistory: string
				/**
				 * V​e​r​ ​ú​l​t​i​m​a​s​ ​r​e​p​r​o​d​u​c​c​i​o​n​e​s
				 */
				latestViews: string
				/**
				 * E​r​r​o​r​ ​a​l​ ​c​a​r​g​a​r​ ​e​l​ ​h​i​s​t​o​r​i​a​l
				 */
				loadError: string
				/**
				 * N​o​ ​h​a​y​ ​n​i​n​g​u​n​a​ ​r​e​p​r​o​d​u​c​c​i​ó​n​.
				 */
				neverPlayed: string
			}
			share: {
				/**
				 * A​u​t​o​p​l​a​y
				 */
				autoplay: string
				/**
				 * I​n​c​l​u​i​r​ ​t​o​k​e​n
				 */
				includeToken: string
			}
			labels: {
				/**
				 * T​í​t​u​l​o
				 */
				title: string
				/**
				 * T​a​g​s
				 */
				tags: string
				/**
				 * I​m​a​g​e​n
				 */
				image: string
				/**
				 * P​e​s​o
				 */
				weight: string
				/**
				 * P​a​t​h
				 */
				path: string
				/**
				 * Q​u​e​r​y
				 */
				query: string
				/**
				 * C​r​e​a​d​o
				 */
				createdAt: string
				/**
				 * A​ñ​a​d​i​d​o
				 */
				addedAt: string
				/**
				 * A​c​t​u​a​l​i​z​a​d​o
				 */
				updatedAt: string
				/**
				 * T​i​e​m​p​o​s
				 */
				timestamps: string
				/**
				 * Ú​l​t​i​m​a​ ​r​e​p​r​o​d​u​c​c​i​ó​n
				 */
				lastTimePlayed: string
				/**
				 * L​a​n​z​a​d​a
				 */
				releasedOn: string
				/**
				 * U​r​l​ ​s​l​u​g
				 */
				slug: string
				/**
				 * V​i​s​i​b​i​l​i​d​a​d
				 */
				visibility: string
			}
		}
		imageCover: {
			/**
			 * E​t​i​q​u​e​t​a
			 */
			label: string
			/**
			 * A​c​t​u​a​l
			 */
			current: string
			/**
			 * R​e​e​m​p​l​a​z​a​r​ ​I​m​a​g​e​n
			 */
			replaceImage: string
			/**
			 * ¿​B​o​r​r​a​r​ ​c​o​v​e​r​?
			 */
			deleteConfirm: string
			/**
			 * E​d​i​t​a​r​ ​C​o​v​e​r
			 */
			edit: string
			/**
			 * N​u​e​v​a​ ​i​m​a​g​e​n
			 */
			'new': string
			/**
			 * S​e​l​e​c​c​i​o​n​a​r​ ​i​m​a​g​e​n
			 */
			select: string
			/**
			 * (​I​m​a​g​e​n​ ​n​o​ ​d​e​f​i​n​i​d​a​)
			 */
			undefined: string
			/**
			 * S​u​b​i​r
			 */
			upload: string
		}
	}
}

export type TranslationFunctions = {
	uikit: {
		forms: {
			errors: {
				/**
				 * Los campos deben coincidir.
				 */
				matchFields: () => LocalizedString
				/**
				 * Campo obligatorio.
				 */
				requiredField: () => LocalizedString
				/**
				 * Formato de email no válido.
				 */
				invalidEmail: () => LocalizedString
			}
			/**
			 * opcional
			 */
			optionalField: () => LocalizedString
			/**
			 * Datos sin guardar.
			 */
			unsavedDataModalTitle: () => LocalizedString
			/**
			 * Hay datos sin guardar.
			 */
			unsavedData: () => LocalizedString
			labels: {
				/**
				 * Nombre
				 */
				name: () => LocalizedString
				/**
				 * Email
				 */
				email: () => LocalizedString
			}
		}
		modals: {
			/**
			 * Confirmar borrado
			 */
			confirmDelete: () => LocalizedString
			/**
			 * ¿Seguro que quieres cerrar?
			 */
			confirmClose: () => LocalizedString
		}
		actions: {
			/**
			 * Guardar
			 */
			save: () => LocalizedString
			/**
			 * Editar
			 */
			edit: () => LocalizedString
			/**
			 * Crear
			 */
			create: () => LocalizedString
			/**
			 * Eliminar
			 */
			'delete': () => LocalizedString
			/**
			 * Cancelar
			 */
			cancel: () => LocalizedString
			/**
			 * Sí
			 */
			confirm: () => LocalizedString
			/**
			 * Cerrar
			 */
			close: () => LocalizedString
			/**
			 * Cambiar
			 */
			change: () => LocalizedString
			/**
			 * Nueva
			 */
			'new': () => LocalizedString
		}
	}
	core: {
		auth: {
			login: {
				/**
				 * Login
				 */
				loginButton: () => LocalizedString
				/**
				 * usuario
				 */
				user: () => LocalizedString
				/**
				 * Email o usuario
				 */
				emailPlaceholder: () => LocalizedString
				/**
				 * Inicia sesión en tu cuenta
				 */
				subtitle: () => LocalizedString
				/**
				 * Iniciando sesión...
				 */
				doingLogin: () => LocalizedString
				/**
				 * Iniciar sesión
				 */
				doLogin: () => LocalizedString
				/**
				 * Accede
				 */
				youDoLogin: () => LocalizedString
				/**
				 * ¿Olvidaste tu contraseña?
				 */
				forgotPassword: () => LocalizedString
				/**
				 * ¿No tienes cuenta?
				 */
				doRegisterAside: () => LocalizedString
				/**
				 * Usuario o contraseña incorrectos.
				 */
				wrongLogin: () => LocalizedString
				/**
				 * Error al iniciar sesión.
				 */
				errorLogin: () => LocalizedString
			}
			register: {
				/**
				 * email
				 */
				email: () => LocalizedString
				/**
				 * Repetir email
				 */
				repeatEmail: () => LocalizedString
				/**
				 * Contraseña
				 */
				password: () => LocalizedString
				/**
				 * Repetir contraseña
				 */
				repeatPassword: () => LocalizedString
				/**
				 * Nombre
				 */
				name: () => LocalizedString
				/**
				 * Apellidos
				 */
				lastname: () => LocalizedString
				/**
				 * Regístrate
				 */
				youDoRegister: () => LocalizedString
				/**
				 * Crear cuenta
				 */
				doRegister: () => LocalizedString
				/**
				 * Creando cuenta...
				 */
				doingRegister: () => LocalizedString
				/**
				 * Nombre de usuario
				 */
				username: () => LocalizedString
				/**
				 * Crea una nueva cuenta
				 */
				subtitle: () => LocalizedString
				/**
				 * ¿Ya tienes cuenta?
				 */
				doLoginAside: () => LocalizedString
				token: {
					/**
					 * Verificando token ...
					 */
					verifying: () => LocalizedString
					/**
					 * Error: Token caducado o incorrecto.
					 */
					error: () => LocalizedString
					/**
					 * Volver a solicitar token
					 */
					requestAgain: () => LocalizedString
				}
				emailVerification: {
					/**
					 * Error en el reenvío
					 */
					errorResending: () => LocalizedString
					/**
					 * Enviado email de verificación
					 */
					resent: () => LocalizedString
					/**
					 * Te hemos enviado un correo a [email] para verificar tu cuenta. Si en unos minutos no lo recibes, haz clic [link] para reenviarlo.
					 */
					sentEmail: () => LocalizedString
					/**
					 * Desactivado temporalmente
					 */
					disabledTitle: () => LocalizedString
					/**
					 * aquí
					 */
					linkText: () => LocalizedString
					/**
					 * Puedes cerrar esta página cuando quieras.
					 */
					subMessage: () => LocalizedString
				}
			}
			logout: {
				/**
				 * Cerrar sesión
				 */
				tab: () => LocalizedString
				/**
				 * Cerrando sesión ...
				 */
				doingLogout: () => LocalizedString
				/**
				 * Error cerrando sesión.
				 */
				errorDoingLogout: () => LocalizedString
			}
		}
		errors: {
			notFound: {
				/**
				 * 😨 Ups... 😨
				 */
				title: () => LocalizedString
				/**
				 * Elemento no encontrado.
				 */
				message: () => LocalizedString
			}
			forbidden: {
				/**
				 * 403 - Acceso Denegado
				 */
				title: () => LocalizedString
				/**
				 * No tienes permisos para acceder a esta página.
				 */
				message: () => LocalizedString
			}
			unauthorized: {
				/**
				 * Sin autorización
				 */
				unauthorized: () => LocalizedString
			}
		}
		user: {
			settings: {
				/**
				 * Ajustes
				 */
				menuLabel: () => LocalizedString
			}
			/**
			 * Menú de usuario
			 */
			menuAriaLabel: () => LocalizedString
			profile: {
				/**
				 * Mi perfil
				 */
				menuLabel: () => LocalizedString
				/**
				 * Perfil
				 */
				title: () => LocalizedString
				/**
				 * Nombre público
				 */
				publicName: () => LocalizedString
				/**
				 * Nombre
				 */
				firstName: () => LocalizedString
				/**
				 * Apellidos
				 */
				lastName: () => LocalizedString
				/**
				 * Roles
				 */
				roles: () => LocalizedString
				/**
				 * Música
				 */
				music: () => LocalizedString
				favoritePlaylist: {
					/**
					 * Playlist favorita
					 */
					favoritePlaylist: () => LocalizedString
					/**
					 * <Ninguna>
					 */
					none: () => LocalizedString
				}
			}
		}
	}
	main: {
		/**
		 * Bienvenido a MCenter
		 */
		welcome: () => LocalizedString
		menu: {
			/**
			 * Inicio
			 */
			home: () => LocalizedString
			/**
			 * Música
			 */
			music: () => LocalizedString
			/**
			 * Series
			 */
			series: () => LocalizedString
			/**
			 * Películas
			 */
			movies: () => LocalizedString
			/**
			 * Remoto
			 */
			remote: () => LocalizedString
		}
		pwa: {
			/**
			 * Instalar shortcut
			 */
			button: () => LocalizedString
			/**
			 * ¿Qué nombre quieres para tu App?
			 */
			appNamePrompt: () => LocalizedString
			/**
			 * Instalar como App
			 */
			title: () => LocalizedString
			/**
			 * Abre en navegador para instalar
			 */
			text: () => LocalizedString
			/**
			 * No se pudo instalar
			 */
			installingError: () => LocalizedString
			/**
			 * Intento de instalación sin evento capturado
			 */
			errorNoEvent: () => LocalizedString
			/**
			 * App instalada con éxito
			 */
			installed: () => LocalizedString
			/**
			 * Instalar App
			 */
			installApp: () => LocalizedString
			/**
			 * La dirección de la App será
			 */
			appAddressWillBe: () => LocalizedString
		}
	}
	common: {
		upload: {
			/**
			 * Tipo desconocido
			 */
			unknownType: () => LocalizedString
			/**
			 * Pendiente de subir
			 */
			pending: () => LocalizedString
			/**
			 * ¡Subido!
			 */
			uploaded: () => LocalizedString
		}
		lists: {
			/**
			 * No hay ningún elemento en esta lista.
			 */
			empty: () => LocalizedString
		}
		dates: {
			/**
			 * hoy
			 */
			today: () => LocalizedString
			/**
			 * ayer
			 */
			yesterday: () => LocalizedString
			/**
			 * Fecha
			 */
			date: () => LocalizedString
			/**
			 * Duración
			 */
			duration: () => LocalizedString
			/**
			 * Hora de reproducción
			 */
			playedAt: () => LocalizedString
		}
	}
	admin: {
		/**
		 * Admin
		 */
		menuLabel: () => LocalizedString
		tasks: {
			tabs: {
				/**
				 * Ejecutar tareas
				 */
				doTasks: () => LocalizedString
				/**
				 * Gestor de tareas
				 */
				taskManager: () => LocalizedString
			}
			/**
			 * No se encontraron tareas.
			 */
			noTasksFound: () => LocalizedString
			/**
			 * Error
			 */
			errorLabel: () => LocalizedString
			/**
			 * Image Covers: rebuild all
			 */
			imageCoversRebuildAll: () => LocalizedString
			episodes: {
				/**
				 * Episodes: updateLastTimePlayed
				 */
				updateLastTimePlayed: () => LocalizedString
				/**
				 * Episodes: update file-info saved
				 */
				fileInfoUpdateSaved: () => LocalizedString
				/**
				 * Episodes: update file infos offloaded
				 */
				updateFileInfosOffloaded: () => LocalizedString
			}
			musics: {
				/**
				 * Musics: search duplicates
				 */
				searchDuplicates: () => LocalizedString
				/**
				 * Musics: update file infos
				 */
				updateFileInfos: () => LocalizedString
				/**
				 * Musics: update file infos offloaded
				 */
				updateFileInfosOffloaded: () => LocalizedString
			}
		}
	}
	modules: {
		player: {
			/**
			 * {{reproductor|reproductores}}
			 */
			player: (arg: { count: number | string | boolean }) => LocalizedString
			remote: {
				/**
				 * Reproductores
				 */
				title: () => LocalizedString
				/**
				 * No se ha detectado ningún reproductor remoto.
				 */
				noPlayers: () => LocalizedString
				status: {
					/**
					 * Offline
					 */
					offline: () => LocalizedString
					/**
					 * Closed
					 */
					closed: () => LocalizedString
					/**
					 * Open
					 */
					open: () => LocalizedString
					/**
					 * Desconocido
					 */
					unknown: () => LocalizedString
				}
				/**
				 * Error parseando datos SSE
				 */
				errorSse: () => LocalizedString
			}
			controls: {
				/**
				 * Anterior
				 */
				prev: () => LocalizedString
				/**
				 * Siguiente
				 */
				next: () => LocalizedString
				/**
				 * Ir atrás 10 segundos
				 */
				rewind10: () => LocalizedString
				/**
				 * Ir adelante 10 segundos
				 */
				forward10: () => LocalizedString
				/**
				 * Detener
				 */
				stop: () => LocalizedString
				/**
				 * Repetición
				 */
				repeat: () => LocalizedString
				/**
				 * Aleatoriedad
				 */
				shuffle: () => LocalizedString
				/**
				 * Cerrar
				 */
				close: () => LocalizedString
				/**
				 * Reproductor completo
				 */
				fullPlayer: () => LocalizedString
				/**
				 * Reproducir
				 */
				play: () => LocalizedString
				/**
				 * Pausar
				 */
				pause: () => LocalizedString
				/**
				 * Reanudar
				 */
				resume: () => LocalizedString
			}
			queue: {
				/**
				 * Lista de reproducción
				 */
				title: () => LocalizedString
				/**
				 * No hay elementos en la lista
				 */
				empty: () => LocalizedString
			}
			effects: {
				/**
				 * Efectos
				 */
				title: () => LocalizedString
			}
			settings: {
				/**
				 * Ir a la playlist
				 */
				goToPlaylist: () => LocalizedString
				/**
				 * Reproducir modificación
				 */
				playModified: () => LocalizedString
			}
		}
		musics: {
			/**
			 * {count} {{canción|canciones}}
			 */
			count: (arg: { count: number }) => LocalizedString
			lists: {
				/**
				 * Listas
				 */
				tab: () => LocalizedString
				playlists: {
					/**
					 * Playlist no encontrada
					 */
					oneNotFound: () => LocalizedString
					/**
					 * Nueva playlist creada
					 */
					oneCreated: () => LocalizedString
					/**
					 * Nueva playlist
					 */
					'new': () => LocalizedString
					/**
					 * Seleccionar playlist
					 */
					select: () => LocalizedString
					/**
					 * Ninguna
					 */
					none: () => LocalizedString
					/**
					 * "{musicTitle}" ya estaba en "{playlistName}" y no se ha añadido.
					 */
					alreadyAdded: (arg: { musicTitle: string, playlistName: string }) => LocalizedString
					/**
					 * "{musicTitle}" añadida a "{playlistName}"
					 */
					added: (arg: { musicTitle: string, playlistName: string }) => LocalizedString
				}
				smartPlaylists: {
					/**
					 * Nueva Smart Playlist creada
					 */
					oneCreated: () => LocalizedString
					/**
					 * Nueva Smart Playlist
					 */
					'new': () => LocalizedString
					/**
					 * Reproducir Smart Playlist
					 */
					play: () => LocalizedString
					/**
					 * Reproducir modificación
					 */
					playModified: () => LocalizedString
					/**
					 * Query inválida
					 */
					invalidQuery: () => LocalizedString
				}
			}
			search: {
				/**
				 * Buscar música...
				 */
				placeholder: () => LocalizedString
				/**
				 * Música no encontrada
				 */
				oneNotFound: () => LocalizedString
			}
			upload: {
				/**
				 * Desde YouTube
				 */
				fromYoutube: () => LocalizedString
				/**
				 * Desde local
				 */
				fromLocal: () => LocalizedString
				/**
				 * Músicas subidas
				 */
				sectionTitle: () => LocalizedString
				/**
				 * No has subido músicas todavía.
				 */
				noneUploaded: () => LocalizedString
				/**
				 * URL del vídeo o playlist
				 */
				youtubeUrlPlaceholder: () => LocalizedString
				/**
				 * (Intento {current}/{max})
				 */
				attempt: (arg: { current: number, max: number }) => LocalizedString
				/**
				 * Procesando tarea
				 */
				processing: () => LocalizedString
				/**
				 * Subir
				 */
				tab: () => LocalizedString
			}
			edit: {
				/**
				 * ¿Estás seguro de borrar esta música?
				 */
				confirmDelete: () => LocalizedString
				/**
				 * Propiedades opcionales
				 */
				optionalProps: () => LocalizedString
				/**
				 * Error al cargar la música
				 */
				loadError: () => LocalizedString
				/**
				 * Desactivado
				 */
				disabled: () => LocalizedString
				/**
				 * Spotify ID
				 */
				spotifyId: () => LocalizedString
				/**
				 * Tags (usa # para tags globales)
				 */
				tagsHint: () => LocalizedString
				/**
				 * Editar archivos
				 */
				editFiles: () => LocalizedString
			}
			info: {
				/**
				 * User Tags
				 */
				userTags: () => LocalizedString
			}
			autoplay: {
				/**
				 * Click para
				 */
				clickTo: () => LocalizedString
				/**
				 * Reproducir música
				 */
				playMusic: () => LocalizedString
			}
			labels: {
				/**
				 * Artista
				 */
				artist: () => LocalizedString
				/**
				 * Álbum
				 */
				album: () => LocalizedString
				/**
				 * Año
				 */
				year: () => LocalizedString
				/**
				 * País
				 */
				country: () => LocalizedString
				/**
				 * Juego
				 */
				game: () => LocalizedString
			}
		}
		episodes: {
			/**
			 * {count} episodio{{s}}
			 */
			count: (arg: { count: number }) => LocalizedString
			edit: {
				/**
				 * ¿Estás seguro de que deseas eliminar este episodio permanentemente?
				 */
				confirmDelete: () => LocalizedString
				/**
				 * Error al cargar el episodio
				 */
				loadError: () => LocalizedString
				/**
				 * Episodio
				 */
				episode: () => LocalizedString
				/**
				 * Hash
				 */
				hash: () => LocalizedString
				/**
				 * Tamaño
				 */
				size: () => LocalizedString
			}
			search: {
				/**
				 * Episodio no encontrado
				 */
				oneNotFound: () => LocalizedString
			}
			series: {
				lists: {
					/**
					 * Explorar
					 */
					tab: () => LocalizedString
				}
				search: {
					/**
					 * Serie no encontrada
					 */
					oneNotFound: () => LocalizedString
				}
				seasons: {
					/**
					 * {count} temporada{{s}}
					 */
					count: (arg: { count: number }) => LocalizedString
					/**
					 * No se encontraron temporadas.
					 */
					noSeasons: () => LocalizedString
				}
				edit: {
					/**
					 * ¿Estás seguro de que deseas eliminar esta serie?
					 */
					confirmDelete: () => LocalizedString
				}
				episodes: {
					/**
					 * No hay episodios en esta temporada.
					 */
					noEpisodes: () => LocalizedString
					/**
					 * Visto por última vez: {date}
					 */
					lastSeen: (arg: { date: unknown }) => LocalizedString
				}
				actions: {
					/**
					 * Comprobar disponibilidad
					 */
					checkAvailability: () => LocalizedString
					/**
					 * Desde local
					 */
					uploadFromLocal: () => LocalizedString
				}
				labels: {
					/**
					 * Nueva serie
					 */
					newTitle: () => LocalizedString
					/**
					 * Editar serie
					 */
					editTitle: () => LocalizedString
					/**
					 * Nombre
					 */
					name: () => LocalizedString
				}
			}
			labels: {
				/**
				 * Key
				 */
				key: () => LocalizedString
				/**
				 * Inicio
				 */
				start: () => LocalizedString
				/**
				 * Fin
				 */
				end: () => LocalizedString
			}
		}
		resources: {
			visibility: {
				/**
				 * Lista pública
				 */
				'public': () => LocalizedString
				/**
				 * Lista privada
				 */
				'private': () => LocalizedString
			}
			history: {
				/**
				 * Historial
				 */
				history: () => LocalizedString
				/**
				 * ¿Borrar entrada?
				 */
				deleteEntry: () => LocalizedString
				/**
				 * Quitar del historial
				 */
				removeFromHistory: () => LocalizedString
				/**
				 * Ver últimas reproducciones
				 */
				latestViews: () => LocalizedString
				/**
				 * Error al cargar el historial
				 */
				loadError: () => LocalizedString
				/**
				 * No hay ninguna reproducción.
				 */
				neverPlayed: () => LocalizedString
			}
			share: {
				/**
				 * Autoplay
				 */
				autoplay: () => LocalizedString
				/**
				 * Incluir token
				 */
				includeToken: () => LocalizedString
			}
			labels: {
				/**
				 * Título
				 */
				title: () => LocalizedString
				/**
				 * Tags
				 */
				tags: () => LocalizedString
				/**
				 * Imagen
				 */
				image: () => LocalizedString
				/**
				 * Peso
				 */
				weight: () => LocalizedString
				/**
				 * Path
				 */
				path: () => LocalizedString
				/**
				 * Query
				 */
				query: () => LocalizedString
				/**
				 * Creado
				 */
				createdAt: () => LocalizedString
				/**
				 * Añadido
				 */
				addedAt: () => LocalizedString
				/**
				 * Actualizado
				 */
				updatedAt: () => LocalizedString
				/**
				 * Tiempos
				 */
				timestamps: () => LocalizedString
				/**
				 * Última reproducción
				 */
				lastTimePlayed: () => LocalizedString
				/**
				 * Lanzada
				 */
				releasedOn: () => LocalizedString
				/**
				 * Url slug
				 */
				slug: () => LocalizedString
				/**
				 * Visibilidad
				 */
				visibility: () => LocalizedString
			}
		}
		imageCover: {
			/**
			 * Etiqueta
			 */
			label: () => LocalizedString
			/**
			 * Actual
			 */
			current: () => LocalizedString
			/**
			 * Reemplazar Imagen
			 */
			replaceImage: () => LocalizedString
			/**
			 * ¿Borrar cover?
			 */
			deleteConfirm: () => LocalizedString
			/**
			 * Editar Cover
			 */
			edit: () => LocalizedString
			/**
			 * Nueva imagen
			 */
			'new': () => LocalizedString
			/**
			 * Seleccionar imagen
			 */
			select: () => LocalizedString
			/**
			 * (Imagen no definida)
			 */
			undefined: () => LocalizedString
			/**
			 * Subir
			 */
			upload: () => LocalizedString
		}
	}
}

export type Formatters = {}
