version: '3.3'

services:
    server:
      build:
        context: .
        dockerfile: Dockerfile
      image: myapp-server-img
      container_name: multimedia-server
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "8200:8080"
      depends_on:
        - mongo
      env_file: .env
      environment:
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
    mongo:
      image: mongo
      container_name: multimedia-db
      ports:
        - "27017:27017"