export {
  assertIsGetAllRequest as assertIsEpisodeGetAllRequest,
  assertIsGetManyBySearchRequest as assertIsEpisodeGetManyBySearchRequest,
  assertIsGetOneByIdRequest as assertIsEpisodeGetOneByIdRequest,
  assertIsPatchOneByIdReqBody as assertIsEpisodePatchOneByIdReqBody,
  assertIsPatchOneByIdRequest as assertIsEpisodePatchOneByIdRequest,
  assertIsPatchOneByIdResBody as assertIsEpisodePatchOneByIdResBody,
  episodeDtoToModel,
  GetAllRequest as EpisodeGetAllRequest,
  GetAllSchema as EpisodeGetAllSchema,
  GetManyBySearchRequest as EpisodeGetManyBySearchRequest,
  GetOneByIdRequest as EpisodeGetOneByIdRequest,
  GetOneByIdSchema as EpisodeGetOneByIdSchema,
  PatchOneByIdReqBody as EpisodePatchOneByIdReqBody,
  PatchOneByIdRequest as EpisodePatchOneByIdRequest,
  PatchOneByIdResBody as EpisodePatchOneByIdResBody,
  PatchOneByIdSchema as EpisodePatchOneByIdSchema,
} from "#shared/models/episodes/dto";
