version: "3.9"

services:
  front:
    image: mcenter/front:latest
    container_name: mcenter_front
    ports:
      - "${MCENTER_FRONT_PORT}:3000"
    restart: always
    depends_on:
      - server

  server:
    image: mcenter/server:latest
    container_name: mcenter_server
    env_file:
      - ../../packages/server/.env
    ports:
      - "${MCENTER_SERVER_PORT}:8080"
    restart: always
    volumes:
      - ${MCENTER_SERVER_MEDIA_PATH}:/home/node/media:ro
      - ../../packages/server/.calendar.js:/packages/app/.calendar.js:ro
      - ../../packages/server/.schedule.js:/packages/app/.schedule.js:ro
      - ../../packages/server/.tag.js:/packages/app/.tag.js:ro

  music:
    image: mcenter/music:latest
    container_name: mcenter_music
    env_file:
      - ../../packages/music/.env
    ports:
      - "${MCENTER_MUSIC_PORT}:8080"
    restart: always
    volumes:
      - ${MCENTER_SERVER_MEDIA_PATH}:/home/node/media:ro

  mongo:
    profiles: ["local"]
    image: mongo:7.0.3
    container_name: mcenter_mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env.db

  mongo-express:
    profiles: ["local"]
    image: mongo-express
    container_name: mcenter_mongo-express
    restart: always
    ports:
      - 8079:8081
    env_file:
      - .env.me
