#!/bin/bash

function is_script_process() {
  local cmdline=$1
  local exe=$(echo "$cmdline" | awk '{ print $1; }')
  local file=$(echo "$cmdline" | awk '{ print $2; }')

  if [ -z "$file" ]; then
    return 0
  fi

  case "$exe" in
  */bash | */sh)
    echo "1"
    ;;
  *)
    echo "0"
    ;;
  esac
}

TRACE=""
CP=$$ # PID of the script itself [1]

while true; do # safe because "all starts with init..."
  CMDLINE=$(cat /proc/"$CP"/cmdline | tr '\0' ' ')
  PP=$(grep PPid /proc/"$CP"/status | awk '{ print $2; }') # [2]
  if [ "$(is_script_process "$CMDLINE")" == "1" ]; then
    TRACE="$TRACE""$CP $CMDLINE\n"
  fi
  if [ "$CP" == "1" ]; then # we reach 'init' [PID 1] => backtrace end
    break
  fi
  CP=$PP
done

# grep not empty lines
echo -e "$TRACE" | sed '1d' | grep -v '^$'
